# Travis CI
language: ruby
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/release
  - chmod a+x script/test
  - bundle update
script: "script/cibuild"
sudo: false
cache: bundler

matrix:
  include:
    - # Ruby 2.2.5
      rvm: 2.2.5
      env: BUNTO_VERSION=3.0.0
  fast_finish: true

rvm:
- 2.3.1
- 2.3.0
env:
  - ""
  - BUNTO_VERSION=3.0.0
  - BUNTO_VERSION=3.2.1
